backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "home"
    delete: false
    editor:
      preview: false
    format: json
    label: "Home Page"
    folder: "src/data/home/"
    create: false
    slug: "data"
    fields:
      - { label: "Heading", name: "heading", widget: "string" }
      - label: "Services"
        name: "services"
        widget: "object"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Paragraph", name: "paragraph", widget: "text" }
          - label: "Links"
            name: "links"
            collapsed: false
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Link/URL", name: "link", widget: "string" }
              - label: "Box Color"
                name: "color"
                widget: "select"
                options:
                  - { label: "Red", value: "#FF8B7D" }
                  - { label: "Blue", value: "#7DB5FF" }
                  - { label: "Orange", value: "#FFC8A5" }
              - label: "Background Image"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: false
      - label: "Who we are"
        name: "who"
        widget: "object"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Paragraph 1", name: "paragraph1", widget: "text" }
          - label: "People"
            name: "people"
            collapsed: false
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Image"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: false
          - { label: "Paragraph 2", name: "paragraph2", widget: "text" }
  - name: "pages"
    label: "Pages"
    folder: "src/data/pages/"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - label: "Path"
        name: "path"
        hint: "This is the slug that appears in the url (e.g. /about, /blog)"
        widget: "string"
      - { label: "Main Body", name: "body", widget: "markdown" }
      - label: "Header Color"
        name: "color"
        widget: "select"
        options:
          - { label: "Red", value: "#FF8B7D" }
          - { label: "Blue", value: "#7DB5FF" }
          - { label: "Orange", value: "#FFC8A5" }
